# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FireChat

  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'JSQMessagesViewController'
pod 'JSONModel'
pod 'Realm'
pod 'SDWebImage', '~> 4.0'
pod 'AFNetworking', '~> 3.0'

  target 'FireChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FireChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
