# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MantlePractice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MantlePractice

pod 'Mantle', '~> 2.1'

  target 'MantlePracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MantlePracticeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
